name: ${PROJECT_NAME} # (0) กำหนดชื่อโปรเจคให้สอดคล้องกับ .env [4]

services:
  # 1. ฐานข้อมูล (Database)
  db-node:
    image: mariadb:10.6
    container_name: ${MY_USERNAME}-db # (1.1) กำหนดชื่อคอนเทนเนอร์ให้สอดคล้องกับ .env [4]
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_pass
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_pass
    networks:
      - backend-zone
    volumes:
      - db-volume:/var/lib/mysql
      - ./sql/script-data.sql:/docker-entrypoint-initdb.d/script-data.sql
    secrets:
      - db_pass

  # 2. ส่วนประมวลผล (Backend)
  backend-php:
    image: bitnami/php-fpm:latest
    container_name: ${MY_USERNAME}-php # (2.1) กำหนดชื่อคอนเทนเนอร์ให้สอดคล้องกับ .env [4]
    volumes:
      - ./app:/var/www/html
    networks:
      - backend-zone
    ##secrets: # (2.3) ถ้าต้องการให้ Backend ใช้รหัสผ่านฐานข้อมูลจาก Secret ให้เปิดบรรทัดนี้และเติมชื่อ Secret ที่ประกาศด้านล่าง [10]
    ##  - db_pass # (2.4) เติมชื่อ Secret ที่ประกาศด้านล่าง [10] 

  # 3. ส่วนรับงานหน้าบ้าน (Web Proxy)
  web-server:
    image: nginx:latest
    container_name: ${MY_USERNAME}-web # (3.2) กำหนดชื่อคอนเทนเนอร์ให้สอดคล้องกับ .env [4]
    volumes:
      - ./app:/var/www/html
    ports:
      - "${HTTP_PORT}:80"  # (3.3) กำหนดพอร์ตให้สอดคล้องกับ .env [4]
    configs:
      - source: my-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend-zone
      - backend-zone
    depends_on:
      - db-node
      - backend-php

  # 4. ส่วนจัดการฐานข้อมูล (phpMyAdmin)
  pwm-tool:
    image: phpmyadmin:latest
    container_name: ${MY_USERNAME}-pma # (4.1) กำหนดชื่อคอนเทนเนอร์ให้สอดคล้องกับ .env [4]
    environment:
      PMA_HOST: db-node
      PMA_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "${PMA_PORT}:80" # (4.4) กำหนดพอร์ตให้สอดคล้องกับ .env [4]
    networks:
      - frontend-zone
      - backend-zone
    secrets:
      - db_pass
    depends_on:
      - db-node

# 5. ส่วนประกาศทรัพยากรส่วนกลาง
networks: 
  frontend-zone:
    driver: bridge
  backend-zone:
    driver: bridge

volumes:
  db-volume:  # (5.1) ชื่อ Named Volume ที่ใช้ให้ตรงกับด้านบน [9]

configs:
  my-nginx-conf:
file: ./_________/shift-nginx.conf # (5.2) เติมชื่อโฟลเดอร์ที่เก็บไฟล์คอนฟิก

secrets:
  db_pass:
file: __________/____________ # (5.3) เติมชื่อโฟลเดอร์และไฟล์ที่เก็บรหัสผ่านของฐานข้อมูล